Merge #60 by angusholder
Fix RSA-KEM decryption to support Android Keystore

Currently `RsaKemHybridDecrypt` appears it should work perfectly on Android Keystore, except that it turns out Android's implementation of RSA private key does not implement `RSAPrivateKey`, only `PrivateKey` and `RSAKey` separately. So when I try to cast the private key obtained from the keystore to `RSAPrivateKey` before using `RsaKemHybridDecrypt`, I get

> java.lang.ClassCastException: android.security.keystore2.AndroidKeyStoreRSAPrivateKey cannot be cast to java.security.interfaces.RSAPrivateKey

This is presumably because keys in Android keystore are non-extractable, so Android keystore cannot implement `RSAPrivateKey.getPrivateExponent`. See [AndroidKeyStoreRSAPrivateKey](https://android.googlesource.com/platform/frameworks/base/+/marshmallow-mr1-release/keystore/java/android/security/keystore/AndroidKeyStoreRSAPrivateKey.java).

This can be fixed by letting `RsaKemHybridDecrypt` accept a `PrivateKey` instead of `RSAPrivateKey` - slightly less type-safe as it will need to cast to `RSAKey` in a couple places, but not all that out of the ordinary for java.security code.

Fortunately Android keystore's RSA public key implementation does not have this same problem, so nothing needs changing in the corresponding `RsaKemHybridEncrypt`.

Does this change look reasonable?

Closes ##60

PiperOrigin-RevId: 817134758
Change-Id: I28ffa8987966fa8631b7c9eca7540006d751be06