Upgrade to latest gradle version
Gradle 7.6 adds support for Java versions up to 19.

Fixes e.g.

```
  java.lang.IllegalArgumentException: Unsupported class file major version 63
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:199)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:180)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:166)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:287)
  	at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
```

sponge/b33492df-8a4b-453d-b9d8-6f4cc359cd10

NO_RELNOTES

PiperOrigin-RevId: 500813290
Change-Id: I759197ab4827f3f016773c1a3d83084c56ed3adc